// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Spawn")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","07/01/2021")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Spawn"
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "07/01/2021"
